# model: gpt-oss:20b
# model: qwen3:30b
model: qwen3:30b-instruct
temperature: 0.3
using_llm: true

input_folder: ./input_files/
output_folder: ./output_files/
job_application_filename: oneio.txt
job_experience_file: job_experience_text.txt
skills_file: skills_text.txt
suggested_skills_file: suggested_skills_text.txt
CV_data: CV_data.yaml
updated_cv_jsonfile: updated_cv_data.json
profile_picture_path: ./input_files/profile_picture.jpg