# model: gpt-oss:20b
model: qwen3:30b
temperature: 0.3

input_folder: ./input_files/
output_folder: ./output_file/
job_application_filename: wartsila_job_appl.txt
job_experience_file: job_experience_text.txt
skills_file: skills_text.txt
suggested_skills_file: suggested_skills_text.txt
CV_data: CV_data.yaml